# Base image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

RUN corepack enable
RUN corepack prepare pnpm@9.12.1 --activate

# Copy package.json and pnpm lock file
COPY pnpm-lock.yaml package.json tsconfig.json vite.config.ts vite.script.config.ts postcss.config.js ./

# Set NODE_ENV to development to install devDependencies
ENV NODE_ENV=development

# Install pnpm and dependencies
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm fetch \
    | grep -v "cross-device link not permitted\|Falling back to copying packages from store"

# Copy the rest of the application code
COPY . .

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm i \
    --frozen-lockfile

# Expose the frontend port
EXPOSE 5100

# Command to run the Remix app with Vite
CMD ["pnpm", "run", "dev"]