# Base image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and pnpm lock file
COPY package.json pnpm-lock.yaml ./

# Install pnpm and dependencies
RUN npm install -g pnpm && pnpm install

# Copy the rest of the application code
COPY . .

# Expose the frontend port
EXPOSE 5100

# Command to run the Remix app with Vite
CMD ["pnpm", "run", "dev"]